### So the first impression is, "Everything is arrays or matrices even images, audios and videos, etc."

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
np.array([1, 4, 45, 5+4j, 29])

array([ 1.+0.j,  4.+0.j, 45.+0.j,  5.+4.j, 29.+0.j])

- **So what numpy is doing here is that it is automatically upcasting the datatype of my data to the datatype which is having a higher order comparatively.**<br>
- **In above case, the moment I entered a complex number in the list, datatype of all elements of the list was upcasted to type "float" from "int".**

In [5]:
np.array([[1, 4, 45, 5+4j, 29, "Suryanshyaknow"]]) #so all elemets are upcasted to object datatype i.e. string.

array([['1', '4', '45', '(5+4j)', '29', 'Suryanshyaknow']], dtype='<U64')

In [8]:
np.array([1, 4, 45, 5+4j, 29, "Suryanshyaknow", [1,2,3,4,5,6]])

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_19692/4044435637.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, 4, 45, 5+4j, 29, "Suryanshyaknow", [1,2,3,4,5,6]])


array([1, 4, 45, (5+4j), 29, 'Suryanshyaknow', list([1, 2, 3, 4, 5, 6])],
      dtype=object)

In [6]:
np.array([1, 4, 45, 5+4j, 29, "Suryanshyaknow", np.array([1,2,3,4,5,6])])

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_1196/1916509671.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([1, 4, 45, 5+4j, 29, "Suryanshyaknow", np.array([1,2,3,4,5,6])])


array([1, 4, 45, (5+4j), 29, 'Suryanshyaknow', array([1, 2, 3, 4, 5, 6])],
      dtype=object)

In [7]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [8]:
#Dimension of this array:
np.array([[1,3],[3,4]]).ndim

2

In [9]:
#no. of elements in this array:
np.array([[1,3],[3,4]]).size

4

In [10]:
#(rows, columns)
np.array([[1,3],[3,4]]).shape

(2, 2)

In [14]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [18]:
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_19692/1655787997.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

- **So here, what this warning is trying to convey is that it might not be persmissible to be having an array having heterogenous dimension, so what it is trying to do is, it is converting the all passed elements of array into list, like it did 5 cells above.**

In [19]:
#So consequently, the dimension of this array is:
np.array([[1,3],[3,4],[6,7,8]]).ndim

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_19692/215437245.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]]).ndim


1

**And consequently, the dimension of the our array becomes one.**

In [20]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [21]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]]).ndim

3

### ndmin:
**int, optional**<br>
&emsp;&emsp;**Specifies the minimum number of dimensions that the resulting array should have.  Ones will be pre-pended to the shape as needed to meet this requirement.**

In [23]:
np.array([1,2,3] , ndmin = 3)

array([[[1, 2, 3]]])

In [26]:
np.array([1,2,3] , ndmin = 3).ndim

3

In [11]:
np.array([1,2,3] , ndmin = 3).shape #Ones will be pre-pended to the shape as needed to meet this requirement.

(1, 1, 3)

### Customized way of setting datatype:

In [28]:
np.array([1,2,3] , dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### We can also pack the elments of an array into tuples (however they will be immutable), let's see:

In [30]:
np.array([(1,3), (3,4)])

array([[1, 3],
       [3, 4]])

**..and no changes observed whatsoever.**

In [12]:
arr = np.array([(1,2) , (4,5)], dtype = [("a",'<i4'), ("b",'<i8')])

In [33]:
type(arr[0][0]) #i4, 4*8=32bits

numpy.int32

In [35]:
type(arr[0][1]) #i8, 8*8=64bits

numpy.int64

**NOTE: We'll never use this concept until and unless we are developing a library.**

In [37]:
arr = np.array([[1,3],[3,4]])
arr

array([[1, 3],
       [3, 4]])

In [15]:
l = [12, 34, 546, 'Suryansh']
l

[12, 34, 546, 'Suryansh']

In [40]:
np.asarray(l)

array(['12', '34', '546', 'Suryansh'], dtype='<U11')

In [47]:
np.mat(l)

matrix([['12', '34', '546', 'Suryansh']], dtype='<U11')

In [16]:
mat = np.asmatrix(l) #converting to matrix.
mat

matrix([['12', '34', '546', 'Suryansh']], dtype='<U11')

### Matrix is the subset of the Array.

### .issubclass():

In [53]:
issubclass(np.matrix, np.ndarray)

True

In [54]:
issubclass(np.ndarray, np.matrix)

False

###  .asanyarray():

In [49]:
np.asanyarray(l) #if not array, will convert into it.

array(['12', '34', '546', 'Suryansh'], dtype='<U11')

In [17]:
np.asanyarray(mat) #if array or its any sub-type, then won't.

matrix([['12', '34', '546', 'Suryansh']], dtype='<U11')

### Shallow Copy and Deep Copy concept:

In [62]:
arr = [[0,1], [1,0]]
arr

[[0, 1], [1, 0]]

In [63]:
a = arr
b = np.copy(arr)

In [64]:
a, b

([[0, 1], [1, 0]],
 array([[0, 1],
        [1, 0]]))

In [68]:
#Lets make some changes in the org value of arr.
arr[0][0] = 56 

In [66]:
a #a is able to reflect those changes.

[[56, 1], [1, 0]]

**a** is **Shallow copy** of **arr**.<br>
**And this is because now, arr and a are pointing to same location and if there are some changes made to that location so both arr and a will be able to reflect them.**

In [67]:
b #while b is not.

array([[0, 1],
       [1, 0]])

**b** is **Deep Copy** of **arr**.<br>
**i.e. a literal copy of arr is made somewhere and now b is pointing to that location. And it goes without saying that b will only reflect changes that will be made to the new location.**

### np.fromfunction(): Constructs an array by executing a function over each coordinate.

In [72]:
np.fromfunction(lambda i,j:i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [75]:
np.fromfunction(lambda i,j:i**j, (3,3)) #by default datatype.

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [76]:
np.fromfunction(lambda i,j:i/j, (3,3)) 

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_19692/1073688577.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j:i/j, (3,3))
C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_19692/1073688577.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j:i/j, (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

### .fromiter(): Create a new 1-dimensional array from an iterable object.

**This is a news! I didn't know that.**

In [26]:
gen=(i**2 for i in range(5))
gen

<generator object <genexpr> at 0x000001F43855CC10>

In [39]:
lc=[i**2 for i in range(5)]
lc #list comprehension

[0, 1, 4, 9, 16]

In [40]:
np.fromiter(lc, dtype=int)

array([ 0,  1,  4,  9, 16])

In [24]:
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [27]:
np.fromiter(gen, dtype=bool)

array([False,  True,  True,  True,  True])

In [99]:
np.fromiter((i**2 for i in range(5)), dtype=int)

array([ 0,  1,  4,  9, 16])

In [100]:
np.fromiter(range(5), dtype=int)

array([0, 1, 2, 3, 4])

### Is range a generator function?
**In Python range objects are not iterators. range is a class of a list of immutable objects. The iteration behavior of range is similar to iteration behavior of list. In list and range we can not directly call next function. We can call next if we get an iterator using iter.**

### .fromstring(): Creating an array from a string. Gotta give the separator val.

In [42]:
np.fromstring('1,3,4,5,6', sep = ',', dtype= int)

array([1, 3, 4, 5, 6])

In [29]:
np.fromstring('1,3,4,5,6', sep = ' ', dtype= int)

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_1196/1625818934.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('1,3,4,5,6', sep = ' ', dtype= int)


array([1])

In [102]:
np.fromstring("456 456 3454 34543", sep = ' ', dtype= complex)

array([  456.+0.j,   456.+0.j,  3454.+0.j, 34543.+0.j])

In [31]:
np.fromstring("456 456 3454 34543", sep = ',', dtype= complex)

C:\Users\SURYAN~1\AppData\Local\Temp/ipykernel_1196/2272772299.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("456 456 3454 34543", sep = ',', dtype= complex)


array([456.+0.j])

### How to read 3D array:

In [107]:
arr = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])
arr

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [109]:
arr.ndim

3

In [114]:
arr.size #16 elements.

16

In [111]:
arr.shape

(2, 2, 4)

**This should be read as 2 arrays of size (2 x 4).**<br>
**Here, 2 can be considered as thickness of the 2D array [[1, 2, 3, 4], [4, 5, 6, 7]] in the 3rd dimesion.**

In [120]:
#4 dimensional array:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [121]:
arr4.shape

(1, 4, 2, 4)

### .arange(): 
- **Return evenly spaced values within a given interval.**
- **Unlike range(), arange() even accepts start, end and step size in float values.**

In [132]:
range(3)

range(0, 3)

In [126]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.arange(8.000000000000001)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [127]:
np.arange(8.9)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [133]:
np.arange(6.7, 8.9)

array([6.7, 7.7, 8.7])

In [134]:
np.arange(6.7, 8.9, 0.5)

array([6.7, 7.2, 7.7, 8.2, 8.7])

In [140]:
np.arange(6.6, 9, 0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

**NOTE: 0.3 is not to be taken as absolute value that's why even upper bound 9 is taken.**

### .linspace()

In [142]:
np.linspace(1,2,5) #Dividing the data between 1 and 2 into 5 equal parts.

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
np.linspace(1,2) #default no. of elements in the array is 50, thus 50 equal parts.

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [145]:
np.linspace(-0.4,2,8)

array([-0.4       , -0.05714286,  0.28571429,  0.62857143,  0.97142857,
        1.31428571,  1.65714286,  2.        ])

**Doubt:**

**If endpoint = False, what should be the end value of an array generated by the .linspace(). Because if endpoint = True we have, say distance between them to be made parts of.**<br>
**In layman terms, what would be our right extreme?**

In [34]:
np.linspace(0, 10, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [162]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [37]:
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [164]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [163]:
np.linspace(1, 10, 5, endpoint=False)

array([1. , 2.8, 4.6, 6.4, 8.2])

In [166]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [165]:
np.linspace(2, 10, 5, endpoint=False)

array([2. , 3.6, 5.2, 6.8, 8.4])

### Transpose of 1D array doesn't exists:

In [180]:
try:
    np.linspace(2, 10, 5, axis=1) #Because the entered array is of 1D type and transpose of 1D array doesn't exist.
except Exception as e:
    print(e)

destination: axis 1 is out of bounds for array of dimension 1


In [6]:
np.linspace([2, 6], 5, 5,axis=0)

array([[2.  , 6.  ],
       [2.75, 5.75],
       [3.5 , 5.5 ],
       [4.25, 5.25],
       [5.  , 5.  ]])

In [7]:
np.linspace([2, 6], 5, 5,axis=1) 

array([[2.  , 2.75, 3.5 , 4.25, 5.  ],
       [6.  , 5.75, 5.5 , 5.25, 5.  ]])

### .zeros(): Return a new array of given shape and type, filled with zeros.

In [167]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [169]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

### .ones(): Return a new array of given shape and type, filled with ones.

In [170]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [172]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [176]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### .empty(): Return a new array of given shape and type, without initializing entries i.e random element values.

In [175]:
np.empty(5)

array([ 2.,  4.,  6.,  8., 10.])

In [174]:
np.empty((1,2))

array([[6.36598737e-314, 8.48798317e-314]])

### .eye(): Returns a identity matrix of entered dimension.

In [177]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(5)*2

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

### .logspace(): Return numbers spaced evenly on a log scale.

In [18]:
np.logspace([2,3], 3, 3, axis=0)

array([[ 100.        , 1000.        ],
       [ 316.22776602, 1000.        ],
       [1000.        , 1000.        ]])

In [21]:
np.logspace([2,3], 4, 3, axis=1)

array([[  100.        ,  1000.        , 10000.        ],
       [ 1000.        ,  3162.27766017, 10000.        ]])

In [30]:
np.logspace([2], [3], 4, axis=0)

array([[ 100.        ],
       [ 215.443469  ],
       [ 464.15888336],
       [1000.        ]])

In [29]:
np.logspace([2,3], 3, 3, axis=1)

array([[ 100.        ,  316.22776602, 1000.        ],
       [1000.        , 1000.        , 1000.        ]])

### .reshape():

In [32]:
x = np.linspace(2,25,20)
x

array([ 2.        ,  3.21052632,  4.42105263,  5.63157895,  6.84210526,
        8.05263158,  9.26315789, 10.47368421, 11.68421053, 12.89473684,
       14.10526316, 15.31578947, 16.52631579, 17.73684211, 18.94736842,
       20.15789474, 21.36842105, 22.57894737, 23.78947368, 25.        ])

In [33]:
x.ndim

1

In [35]:
x.shape

(20,)

In [40]:
x.reshape(1,1,20)

array([[[ 2.        ,  3.21052632,  4.42105263,  5.63157895,
          6.84210526,  8.05263158,  9.26315789, 10.47368421,
         11.68421053, 12.89473684, 14.10526316, 15.31578947,
         16.52631579, 17.73684211, 18.94736842, 20.15789474,
         21.36842105, 22.57894737, 23.78947368, 25.        ]]])

In [36]:
x.reshape(5,4) 

array([[ 2.        ,  3.21052632,  4.42105263,  5.63157895],
       [ 6.84210526,  8.05263158,  9.26315789, 10.47368421],
       [11.68421053, 12.89473684, 14.10526316, 15.31578947],
       [16.52631579, 17.73684211, 18.94736842, 20.15789474],
       [21.36842105, 22.57894737, 23.78947368, 25.        ]])

In [41]:
x.reshape(10,1,2) 

array([[[ 2.        ,  3.21052632]],

       [[ 4.42105263,  5.63157895]],

       [[ 6.84210526,  8.05263158]],

       [[ 9.26315789, 10.47368421]],

       [[11.68421053, 12.89473684]],

       [[14.10526316, 15.31578947]],

       [[16.52631579, 17.73684211]],

       [[18.94736842, 20.15789474]],

       [[21.36842105, 22.57894737]],

       [[23.78947368, 25.        ]]])

### np.random.rand()

In [48]:
np.random.rand(3) #Random values in a given shape.

array([0.66381962, 0.74781977, 0.70801191])

In [50]:
np.random.rand(2,3,3)

array([[[0.49203936, 0.68987959, 0.1832852 ],
        [0.91418838, 0.84195741, 0.35581714],
        [0.72367301, 0.83194475, 0.0042029 ]],

       [[0.10567503, 0.39575175, 0.5926357 ],
        [0.49430806, 0.36355452, 0.51544635],
        [0.55661395, 0.02217789, 0.5700007 ]]])

In [47]:
np.random.randn(3) #Returns a sample (or samples) from the "standard normal" distribution.

array([-1.28750206, -0.40761027,  0.83597795])

In [51]:
np.random.randn(2,3,3)

array([[[-1.08488361, -0.14052412,  0.22452383],
        [-1.36295719,  0.14457488, -0.67463294],
        [ 0.29767901,  0.89685936, -0.89732606]],

       [[ 1.10914396, -1.06970707, -0.58660842],
        [ 0.92045638, -0.58580723, -0.3438161 ],
        [-0.28827368, -2.06314489, -0.13453842]]])

In [56]:
np.random.randint(10,20) #Return random integers from `low` (inclusive) to `high` (exclusive).

15

In [57]:
np.random.randint(10,20, (3,3))

array([[15, 12, 18],
       [16, 17, 16],
       [12, 10, 18]])

In [58]:
np.random.randint(10,20, (2,3,3))

array([[[15, 15, 19],
        [10, 18, 13],
        [17, 19, 13]],

       [[14, 13, 12],
        [18, 15, 10],
        [17, 14, 16]]])

In [60]:
arr=np.random.randint(1,50, (3,3))
arr

array([[ 6, 23,  8],
       [48, 38, 36],
       [44, 27, 13]])

**Trick:**

In [61]:
arr.reshape(1, -54345356) #it's able to predict the second number on its own.

array([[ 6, 23,  8, 48, 38, 36, 44, 27, 13]])

In [62]:
arr.reshape(3, -54345356)

array([[ 6, 23,  8],
       [48, 38, 36],
       [44, 27, 13]])

## Extracting specific elements from the matrix:

In [70]:
mat=np.random.randint(12, 100, (5,5))
mat

array([[80, 99, 84, 88, 14],
       [47, 41, 32, 64, 49],
       [69, 99, 47, 13, 68],
       [43, 72, 42, 84, 53],
       [62, 61, 74, 12, 60]])

In [71]:
mat[3:, 3:]

array([[84, 53],
       [12, 60]])

In [74]:
mat>50

array([[ True,  True,  True,  True, False],
       [False, False, False,  True, False],
       [ True,  True, False, False,  True],
       [False,  True, False,  True,  True],
       [ True,  True,  True, False,  True]])

In [75]:
mat[mat>50]

array([80, 99, 84, 88, 64, 69, 99, 68, 72, 84, 53, 62, 61, 74, 60])

## Matrix Multiplication: 

In [76]:
A=np.random.randint(12, 100, (3,3))
B=np.random.randint(12, 100, (3,3))
A, B

(array([[39, 76, 13],
        [95, 25, 20],
        [40, 99, 77]]),
 array([[27, 87, 32],
        [63, 27, 57],
        [33, 12, 63]]))

In [77]:
A*B

array([[1053, 6612,  416],
       [5985,  675, 1140],
       [1320, 1188, 4851]])

### This ain't the multiplication we were expecting. It won't do any good.

In [79]:
A@B #Our legit multiplication.

array([[ 6270,  5601,  6399],
       [ 4800,  9180,  5725],
       [ 9858,  7077, 11774]])

In [80]:
A=np.random.randint(12, 100, (3,2))
B=np.random.randint(12, 100, (2,3))
A, B

(array([[74, 20],
        [37, 39],
        [64, 61]]),
 array([[40, 79, 53],
        [82, 66, 93]]))

In [81]:
try:
    A*B
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (3,2) (2,3) 


In [82]:
A@B

array([[4600, 7166, 5782],
       [4678, 5497, 5588],
       [7562, 9082, 9065]])

## Broacasting:

In [92]:
arr = np.array([100, 200, 300])
B

array([[40, 79, 53],
       [82, 66, 93]])

### Row-wise Broadcasting:

In [93]:
B + arr #broadcasted the arr to each row of the mat B.

array([[140, 279, 353],
       [182, 266, 393]])

### Column-wise Broadcasting:

In [95]:
arr1 = np.random.randint(10, 99, (2,1))
arr1

array([[31],
       [87]])

In [97]:
B + arr1 #broadcasted the arr1 to each column of the mat B.

array([[ 71, 110,  84],
       [169, 153, 180]])

In [98]:
arr1.T #transpose

array([[31, 87]])

In [101]:
arr2 = np.random.randint(50,99, (5, 4))
arr2

array([[72, 69, 95, 68],
       [57, 87, 87, 72],
       [76, 97, 52, 66],
       [60, 91, 90, 61],
       [52, 96, 69, 76]])

In [102]:
np.sqrt(arr2)

array([[8.48528137, 8.30662386, 9.74679434, 8.24621125],
       [7.54983444, 9.32737905, 9.32737905, 8.48528137],
       [8.71779789, 9.8488578 , 7.21110255, 8.1240384 ],
       [7.74596669, 9.53939201, 9.48683298, 7.81024968],
       [7.21110255, 9.79795897, 8.30662386, 8.71779789]])

In [103]:
np.log10(arr2)

array([[1.8573325 , 1.83884909, 1.97772361, 1.83250891],
       [1.75587486, 1.93951925, 1.93951925, 1.8573325 ],
       [1.88081359, 1.98677173, 1.71600334, 1.81954394],
       [1.77815125, 1.95904139, 1.95424251, 1.78532984],
       [1.71600334, 1.98227123, 1.83884909, 1.88081359]])

In [104]:
np.exp(arr2)

array([[1.85867175e+31, 9.25378173e+29, 1.81123908e+41, 3.40427605e+29],
       [5.68572000e+24, 6.07603023e+37, 6.07603023e+37, 1.85867175e+31],
       [1.01480039e+33, 1.33833472e+42, 3.83100800e+22, 4.60718663e+28],
       [1.14200739e+26, 3.31740010e+39, 1.22040329e+39, 3.10429794e+26],
       [3.83100800e+22, 4.92345829e+41, 9.25378173e+29, 1.01480039e+33]])

### .random.seed(): To fixate the random generated data.

In [108]:
np.random.seed(13) #For every seed value the data will be different, but can be fixated using these seed values.
np.random.randint(56, 59, (3,3))

array([[58, 56, 58],
       [56, 58, 58],
       [56, 57, 56]])

In [109]:
np.random.seed(17) #For every seed value the data will be different, but can be fixated using these seed values.
np.random.randint(56, 59, (3,3))

array([[57, 58, 58],
       [57, 56, 57],
       [58, 56, 56]])

### Solve linear equation for x:

In [52]:
#20x + 10y = 350
#17x + 22y = 500
A = np.array([[20,10], [17,22]])
B = np.array([350, 500])

print(f"A: {A}\nB: {B}")

A: [[20 10]
 [17 22]]
B: [350 500]


In [56]:
xy = np.linalg.solve(A, B)
xy #(x, y)

array([10., 15.])